apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyrsia-build-service.name" . }}
spec:
  selector:
    app: {{ include "pyrsia-build-service.name" . }}
    tier: backend
  ports:
    - name: build-service
      protocol: TCP
      port: 80
      targetPort: 8080
